### ISSUE TITLE
Create animated instructions for the game

### ISSUE THREAD

**Issue by ravish84** [ravish84/test-repo#5]
**Description**
Change the current instructions to include some animations in how to play page

**Why is this important?**
- This will make user onboarding easier 

**Key Notes**
- Take screenshots and use them to create gifs

**Task List**

- [x] Create the draft gif instructions
- [x] Create final gif for each steps
- [x] Put gif in production
